### ISSUE TITLE
Integration with RESTful module

### ISSUE THREAD

**Issue by xuxucode** [INsReady/DrupalCloud#12]
There is a new [RESTful](https://www.drupal.org/project/restful) module, it seems more flexible and powerful than services and restws.

**Comment by skyred** [comment]
100% agreed. See https://github.com/INsReady/DrupalCloud/releases

**Comment by xuxucode** [comment]
@skyred sorry, I mean [https://www.drupal.org/project/restful](https://www.drupal.org/project/restful), not [https://www.drupal.org/project/restws](https://www.drupal.org/project/restws).

 restws is a good choice, but **restful** may be a better choice for its flexibility.

**Comment by skyred** [comment]
@edwardaa Sorry, I didn't realize the new module. I just read https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/README.md. I have mixing feeling about the the direction the module is going. I will put my discussion on that module on the Drupal side instead of here.

But, for now, the direction of DrupalCloud is to support Drupal 8, and that means it will support restws in D7 (since rest in D8 is based on restws module). For RESTful module, I am marking it down as won't fix.
